name: event-pipe
main: index.js
version: 0.0.3
description: a simple event pipe, make async easy to use.
author:
  name: 清笃
  email: qingdu@alibaba-inc.com
engines:
  node: >=0.6.0
homepage: http://github.com/q3boy/event-pipe
repository:
  type: git
  url: git://github.com/q3boy/event-pipe.git
bugs:
  url: http://github.com/q3boy/event-pipe/issues
devDependencies:
  jake-tools: >=0.0.9
  expect.js: >=0.2.0
  yamljs: >=0.1.3
  jake: >=0.5.0
scripts:
  prepublish: make all
  postpublish: make clean
  test: jake coverage
